gst_pipes_node:
  ros__parameters:


    gst_plugin_paths:
      - 'install/gst_bridge/lib/gst_bridge/'
    # XXX use the colcon package finder too

    #pipeline_base_descr: "appsrc name='mysrc' ! appsink name='mysink'"
    #pipeline_base_descr: ""
    pipeline_base_descr: "videotestsrc name=mysrc ! videoconvert ! rosimagesink name=mysink"
    #pipeline_base_descr: "videotestsrc name=mysrc ! videoconvert ! ximagesink name=mysink"

    ros_plugin_names:
      - "appsrc_handler"
      - "appsink_handler"

    appsrc_handler:
      type: "gst_pipes::gst_pipes_appsrc"
      appsrc_name: "mysrc"

    appsink_handler:
      type: "gst_pipes::gst_pipes_appsink"
      appsink_name: "mysink"

